(in-package #:scenic)

(defgeneric free (obj))
(defmethod free (obj) t)
(defmethod free ((obj null)) t)
(defmethod free ((obj list))
  (mapc #'free obj))

(defun slynk-hook ()
  #+slynk
  (slynk-mrepl::send-prompt (find (bt:current-thread) (slynk::channels)
                                  :key #'slynk::channel-thread)))

(defun init-all-the-things ()
  (init-state
   (list (make-material :roughness .8 :metallic .02 :specular .1)
         (make-material :roughness .4 :metallic .4  :specular .1)))
  (let ((s1 (make-scene-ode :color (v! .2 .2 .2 1) :post (list (make-defer-postprocess)))))
    (register (make-defered :downscale .25 :pos (v! 2 2 2) :rot (q:point-at (v! 0 1 0) (v! 2 2 2) (v! 0 0 0))) s1)
    (register (make-point :pos (v! 2 1 2) :color (v! .3 .4 .1)) s1)
    (register (make-point :pos (v! -2 2 -2) :color (v! .1 .1 .3) :linear 0.35 :quadratic 0.44) s1)
    (register s1 *state*)))

(defclass tick (event)
  ((tt :initarg :tt :reader tt)
   (dt :initarg :dt :reader dt)
   (fc :initarg :fc :reader fc)))

(def-simple-main-loop play-render (:on-start #'init)
  (main-loop))

(let ((fc 0)
      (tt 0.0d0)
      (dt 0.0d0)
      (current-time (current-time)))
  (declare (type double-float current-time tt dt))
  (defun init ()
    (setf fc 0 tt 0.0d0 current-time (current-time))
    (slynk-hook)
    (free *state*)
    (ode-stop-world)
    (reset-material-counter)
    (skitter-cleanup)
    (skitter:listen-to #'window-listener-trampoline (skitter:window 0) :size)
    (ode-init-world)
    (init-all-the-things)
    (setf (last-time *state*) (get-internal-real-time)))
  (defun main-loop ()
    (let* ((scene  (current-scene))
           (camera (active-camera scene)))
      (when (zerop (mod fc 10))
        (setf current-time (current-time))
        (setf dt (- tt current-time .001d0))
        (setf dt (if (> dt .16d0) .00001d0 dt))
        (setf tt current-time)
        (issue scene 'tick :tt tt :dt dt :fc fc))
      (upload scene)
      (update scene dt)
      (rocket-update)
      (decay-events)
      ;; Lights/Shadows
      (dolist (l (remove-if #'point-p (lights scene)))
        (draw scene l dt))
      (when-let ((points (remove-if-not #'point-p (lights scene))))
        (let ((1-point (first points)))
          (when (drawp 1-point)
            (clear-fbo (fbo 1-point) :d)
            (dolist (p points)
              (print (list scene p))
              (trace paint :methods t)
              (trace draw :methods t)
              (draw scene p dt)
              (untrace draw)
              (untrace paint))
            (setf (drawp (first points)) NIL))))
      (draw scene camera dt)
      (process scene)
      (incf fc)
      (as-frame
        (blit scene (post scene) camera dt)
        ;;(draw-tex-tr (first (sam (alexandria:lastcar (actors scene)))))
        ;;(draw-tex-br (first (sam camera))); ALBEDO
        ;;(draw-tex-bl (second (sam camera))); NORMALS?
        ;; (draw-tex-tr (third (sam camera))); POSITION?
        ;;(draw-tex-tl (fourth (sam camera)));; ???
        ;; (draw-tex-tr (first (sam (capture    scene))))
        ;; (draw-tex-tl (first (sam (prefilter  scene))))
        ;; (draw-tex-bl (first (sam (irradiance scene))))
        ;; (draw-tex-br (first (sam *irradiance*)))
        ;;(draw-tex-tl (first (sam camera)) :color-scale (v! 10 10 10 1) )
        ;;(draw-tex-br (spot-sam *state*)))
        ;;(draw-tex-br (point-sam *state*)  :index 0)
        ;;(draw-tex-br (dir-sam *state*)) :index 0)
        ))))

(defun start ()
  (play-render :start))

(defun stop ()
  (play-render :stop))
