name: Linux Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: molochwalker/gantoo:glibc
    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          lfs: true

      - name: mkdir
        run: |
          mkdir -pv /tmp/binpkgs
          mkdir -pv ~/Downloads
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
        shell: bash
      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-gantoo-glibc
        with:
          path: |
            /tmp/binpkgs/
            /var/db/repos/gentoo/
            ~/Downloads/
            ~/quicklisp
            ~/.cache/common-lisp/
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      - name: PORTAGE deps
        env:
          PKGDIR: /tmp/binpkgs
        run: |
          emerge-webrsync
          emerge --quiet-build=y -j2 -l2 -bk media-libs/libsdl2 media-libs/assimp media-libs/openal

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          source /etc/profile
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)' \
               --eval '(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt" :replace t :prompt nil)'
        if: steps.cache.outputs.cache-hit != 'true'

      # both below due quicklisp is a couple of months old as of right now (june 23)
      # log4cl added due https://github.com/sharplispers/log4cl/issues/45#issuecomment-1493418045
      # classimp added for assimp v5 support https://github.com/3b/classimp/issues/18
      - name: Get LISP deps
        run: |
          cd ~/quicklisp/local-projects/
          (test -d nepal)     || git clone --depth=1 https://github.com/azimut/nepal
          ( cd nepal/     ; git pull )
          (test -d rocketman) || git clone --depth=1 https://github.com/azimut/rocketman
          ( cd rocketman/ ; git pull )
          (test -d cepl)      || git clone --depth=1 https://github.com/azimut/cepl
          ( cd cepl/      ; git pull )
          (test -d glsl-spec) || git clone --depth=1 https://github.com/azimut/glsl-spec
          ( cd glsl-spec/ ; git pull )
          (test -d cepl.fond) || git clone --depth=1 https://github.com/cbaggers/cepl.fond
          ( cd cepl.fond/ ; git pull )
          (test -d classimp)  || git clone --depth=1 https://github.com/3b/classimp
          ( cd classimp/  ; git pull )
          (test -d cm)        || git clone --depth=1 https://github.com/ormf/cm
          ( cd cm/        ; git pull )
          (test -d log4cl)    || git clone --depth=1 https://github.com/sharplispers/log4cl
          ( cd log4cl/    ; git pull )

      - name: Build Binary
        run: |
          source /etc/profile
          cd bin/
          make scenic.AppImage

      - name: Dev Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: true
          title: "Development Linux Build"
          files: |
            bin/scenic.AppImage
            LICENSE

      - name: Stable Release
        uses: marvinpinto/action-automatic-releases@latest
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            bin/scenic.AppImage
            LICENSE

      - name: DEBUG SHELL
        uses: seemethere/action-tmate@skip_dependency_installation
        if: ${{ failure() }}
        with:
          install_dependencies: false
          sudo: false
