name: Build scenic

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y libassimp4 libsdl2-dev sbcl wget
          mkdir -pv ~/Downloads
          mkdir -pv ~/sbcl
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
        shell: bash

      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache SBCL Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-sbcl
        with:
          path: |
            ~/Downloads/
            ~/quicklisp
            ~/.cache/common-lisp/
            ~/sbcl
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"
      - name: Restore Path To Cached Files
        run: |
          echo $HOME/sbcl/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'

      - name: Download SBCL
        run: |
          cd ~/Downloads
          wget http://downloads.sourceforge.net/project/sbcl/sbcl/2.1.9/sbcl-2.1.9-source.tar.bz2
          tar xjf sbcl-2.1.9-source.tar.bz2
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install SBCL
        run: |
          cd ~/Downloads/sbcl-2.1.9
          sh make.sh
          unset SBCL_HOME
          INSTALL_ROOT=~/sbcl ./install.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Get LISP deps
        run: |
          cd ~/quicklisp/local-projects/
          (test -d rocketman) || git clone https://github.com/azimut/rocketman
          (test -d rocketman) && ( cd rocketman; git pull https://github.com/azimut/rocketman)
          (test -d cepl) || git clone https://github.com/azimut/cepl
          (test -d cepl)  && ( cd cepl ; git pull https://github.com/azimut/cepl)
          (test -d glsl-spec)  || git clone https://github.com/azimut/glsl-spec
          (test -d glsl-spec)  && ( cd glsl-spec ; git pull https://github.com/azimut/glsl-spec)

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          export PATH="$HOME/sbcl/bin:${PATH}"
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --disable-debugger \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)' \
               --eval '(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt" :replace t :prompt nil)' \
               --quit

      - name: Build Binary
        run: |
          export PATH="$HOME/sbcl/bin:${PATH}"
          cd bin/
          make scenic

      - uses: actions/upload-artifact@v2
        with:
          name: scenic-linux
          path: |
            bin/scenic
            bin/*.so*
            bin/Makefile
          if-no-files-found: error
